<h4>Slovenska verzija (SI)</h4>
<h5>1 - Pogoji uporabe</h5>
<p>1.1 - Z uporabo te spletne aplikacije ("spletne strani", "spletne aplikacije", "aplikacije", "rkjsezana.app", "storitve", "spletne storitve") se strinjate z sledečimi pogoji uporabe, vse veljavnimi zakoni in predpisi, ter se strinjate, da ste sami odgovorni za skadnost z veljavnimi lokalnimi zakoni. Če se ne strinjate s katerim koli delom pogojev uporabe vam je prepovedana uporaba storitve ter dostop do kakršnega koli materjala, ki ga storitev ponuja ali hrani.</p>
<p>1.2 - Storitev rkjsezana.app si pridžuje pravico do hranjenja katerih koli podatkov do katerih lahko dostopa ali ste jih ali boste kadarkoli posredovali sistemu.</p>
<h5>2 - Odpoved odgovornosti</h5>
<p>2.1 - Vso gradiva in podatki, ki so na voljo na rkjsezana.app, so podani "kot so". Storitev rkjsezana.app ne jamči, da bi bili vsi podatki posodobljeni ter točni.</p>
<h5>3 - Politika zasebnosti</h5>
<p>3.1 - Vaša zasebnost je za nas zelo pomembna. Skladno s tem smo razvili ta pravilnik, da boste lahko razumeli, kako zbiramo, uporabljamo, komuniciramo in razkrivamo ter uporabimo osebne podatke. V nadaljevanju je opisana naša politika zasebnosti.</p>
<p>3.2 - Pred ali med zbiranjem osebnih podatkov bomo identificirali namene, za katere se zbirajo informacije.</p>
<p>3.3 - Vsi osebni podatki se zbirajo in uporabljajo izključno z namenom zagotavljanja najboljše uporabniške izkušnje.</p>
<p>3.4 - Vsi občutljivi osebni podatki, ki vključujejo, vendar niso omejeni na gesla, so hranjeni, v določenih slučajih tudi kriptirani, v zaščiteni bazi podatkov ter ne bodo posredovani storitvam tretjih oseb.</p>
<h5>4 - Piškotki</h5>
<p>4.1 - Za boljšto uporabniško izkušnjo, spletna storitev rkjsezana.app uporablja spletne piškotke. Z uporabno te strani se prezpogojno strinjate z uporabno spletnik piškotkov ter hranjenjem spletnik piškotnov v vašem brskalniku.</p>
<h5>5 - Uporabniško soglasje</h5>
<p>5.1 - Razumete in se strinjate, da je uporaba te spletne strani in kakršnih koli storitev ali vsebine, ki so vam na voljo, na voljo na lastno odgovornost. To vam je zagotovljeno, kot je, in izrecno odpovedujemo vso garancijo katerekoli vrste, izražene ali implicitne, vključno, a ne omejeno na garancije glede prodajnosti, primernosti za določen namen in nekršitve. Razumete in se strinjate, da niti mi niti kateri koli udeleženec storitve ne nudimo nobenega strokovnega nasveta, zato je uporaba takega nasveta ali kakršnih koli drugih informacij izključno na lastno odgovornost in brez kakršne koli prevzemanja odgovornosti z naše stani. Nekatere jurisdikcije morda ne dovoljujejo zavrnitve implicitnih jamstev in zgornja izjava o omejitvi odgovornosti morda ne velja le za vas, ker se nanaša na implicitne garancije.</p>
<p>5.2 - Izrecno razumete in se strinjate, da ne bomo odgovorni za kakršno koli neposredno, posredno, posebno, naključno, posledično ali zgledno škodo, vključno, vendar ne omejeno na škodo zaradi izgube dobička, dobrega imena, uporabe podatkov ali druge neopredmetene izgube (tudi če smo bili seznanjeni z možnostjo takšne škode), ki izhaja iz (I) uporabe ali nezmožnosti uporabe storitve, (II) stroškov za pridobitev nadomestnega blaga in / ali storitev, ki izhajajo iz kakršne koli transakcije, ki je bila vnesena v storitev ali preko storitve, (III) nepooblaščen dostop do vaših podatkov ali njihovo spreminjanje, (IV) izjave ali ravnanje katere koli tretje stranke v službi, ali (V) katero koli drugo zadevo v zvezi s storitvijo. Upoštevajte, da s sprejetjem pogojev v dokumentu se prav tako odpovedujete svoji pravici, ukrepanji, zakonito, nezakonito ali kako drugače, proti vsakomur ali kaj drugega povezano z administratorji, člani ali uporabniki te storitve. Poleg tega priznavate, da če je kateri koli del tega dokumenta ugotovljen kot neveljaven ali neizvedljiv na noben način, se bodo vsi deli, ki se ne štejejo za neveljavne ali neizvršljive, šteli kot popolnoma veljavni in zavezujoči.</p>
<p>5.3 - V primeru da se ne strinjate s pogoji uporabe vam je odvzeta kakršna koli pravica uporabe kakršnih koli storitev, ki so v, posredni ali neposredni, povezavi s spletno storitvijo RKJSEZANA.APP</p>
<hr>
<h4>English version (EN)</h4>
<h5>1 - Terms of usage</h5>
<p>1.1 - By accessing this website, you are agreeing to be bound by these website’s Terms and Conditions of Use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not or have failed to comply with any of our terms and conditions you are prohibited from using or accessing this site and/or the entirety of our services.</p>
<p>1.2 - We ( "we", "us", "rkjsezana.app", "our", "ours", "this service", "the service") reserve the right to store any data that you might provide at any point of using our service</p>
<h5>2 - Disclaimer</h5>
<p>2.1 - All the material and data provided on rkjsezana.app service is provided "as is". rkjsezana.app service makes no warranties for keeping all the data up to date and accurate.</p>
<h5>3 - Privacy policy</h5>
<p>3.1 - Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.</p>
<p>3.2 - Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.</p>
<p>3.3 - All personal data is being and will be collected and used solely with the objective of providing best user experience.</p>
<p>3.4 - All sensitive personal data, that includes, but is not limited to passwords, will be kept encrypted in a secured database and will not be redistributed to any third party services.</p>
<h5>4 - Cookies</h5>
<p>4.1 - For better user experience we are using cookies. By using this site, you are unconditionally agreeing to use of online cookies and storing cookies and their data in your browser and/or browser's data folder.</p>
<h5>5 - User agreement</h5>
<p>5.1 - You understand and agree that your use of this website and any services or content provided is made available and provided to you at your own risk. It is provided to you as-is and we expressly disclaim all warranties of any kind, expressed or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose, and non-infringement. You understand and agree that neither us nor any participant in the service provides professional advice of any kind and thus use of such advice or any other information is solely at your own risk and without our liability of any kind. Some jurisdictions may not allow disclaimers of implied warranties and the above disclaimer may not apply to you only as it relates to implied warranties.</p>
<p>5.2 - You expressly understand and agree that we shall not be liable for any direct, indirect, special, incidental, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible loss (even if we have been advised of the possibility of such damages), resulting from or arising out of (I) The use of or the inability to use the service, (II) The cost to obtain substitute goods and/or services resulting from any transaction entered into or through the service, (III) Unauthorized access to or alteration of your data transmissions, (IV) Statements or conduct of any third party on the service, or (V) any other matter relating to the service. Note that by accepting the terms in the document, you are also waiving your right, to take any action, legal or otherwise, against anyone or anything related to the administrators, members or any users of this service. You furthermore acknowledge that if any part of this document is found to be invalid or unenforceable in any way, any parts not found to be invalid or unenforceable will be considered fully valid and binding.</p>
<p>5.3 - In case you do not agree with terms of usage you are not allowed to use or interract with any service provided or associated with web service RKJSEZANA.APP</p>
